spring.application.name=Jsp_College_System
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

logging.level.org.springframework.web.servlet.view=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
